<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('quran_sessions', function (Blueprint $table) {
            // Add reference to individual circles
            $table->foreignId('individual_circle_id')->nullable()->constrained('quran_individual_circles')->onDelete('cascade')->after('circle_id');
            
            // Update session_type to be more specific
            $table->enum('session_type', [
                'individual',           // Individual circle session
                'group',               // Group circle session (was 'circle')
                'makeup',              // Makeup session
                'trial',               // Trial session
                'assessment'           // Assessment session
            ])->default('individual')->change();
            
            // Add fields to distinguish between template and actual sessions
            $table->boolean('is_template')->default(false)->after('session_type'); // For individual circle sessions created with subscription
            $table->boolean('is_generated')->default(false)->after('is_template'); // For group circle sessions generated by cron
            $table->foreignId('generated_from_schedule_id')->nullable()->constrained('quran_circle_schedules')->onDelete('set null')->after('is_generated');
            
            // Add scheduling flags
            $table->boolean('is_scheduled')->default(false)->after('status'); // Has teacher set specific date/time
            $table->datetime('teacher_scheduled_at')->nullable()->after('is_scheduled'); // When teacher scheduled it
            $table->foreignId('scheduled_by')->nullable()->constrained('users')->onDelete('set null')->after('teacher_scheduled_at');
            
            // Update status to include template state
            $table->enum('status', [
                'template',            // Created but not scheduled (individual circles)
                'scheduled',           // Teacher has set date/time
                'ongoing',             // Currently happening
                'completed',           // Finished
                'cancelled',           // Cancelled
                'missed',              // Student didn't attend
                'rescheduled',         // Moved to different time
                'pending'              // Awaiting confirmation
            ])->default('template')->change();
            
            // Add session sequence for individual circles
            $table->integer('session_sequence')->nullable()->after('session_code'); // 1st, 2nd, 3rd session etc.
            
            // Improve indexes for new queries
            $table->index(['individual_circle_id', 'status']);
            $table->index(['is_template', 'quran_teacher_id']);
            $table->index(['is_generated', 'generated_from_schedule_id']);
            $table->index(['is_scheduled', 'scheduled_at']);
            $table->index(['session_type', 'status', 'scheduled_at']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('quran_sessions', function (Blueprint $table) {
            // Remove new foreign keys first
            $table->dropForeign(['individual_circle_id']);
            $table->dropForeign(['generated_from_schedule_id']);
            $table->dropForeign(['scheduled_by']);
            
            // Remove new indexes
            $table->dropIndex(['individual_circle_id', 'status']);
            $table->dropIndex(['is_template', 'quran_teacher_id']);
            $table->dropIndex(['is_generated', 'generated_from_schedule_id']);
            $table->dropIndex(['is_scheduled', 'scheduled_at']);
            $table->dropIndex(['session_type', 'status', 'scheduled_at']);
            
            // Remove new columns
            $table->dropColumn([
                'individual_circle_id',
                'is_template',
                'is_generated',
                'generated_from_schedule_id',
                'is_scheduled',
                'teacher_scheduled_at',
                'scheduled_by',
                'session_sequence'
            ]);
            
            // Restore original enums
            $table->enum('session_type', [
                'individual',
                'circle',
                'makeup',
                'trial',
                'assessment'
            ])->default('individual')->change();
            
            $table->enum('status', [
                'scheduled',
                'ongoing',
                'completed',
                'cancelled',
                'missed',
                'rescheduled',
                'pending'
            ])->default('scheduled')->change();
        });
    }
};