@php
    // Get gradient palette
    $gradientPalette = $academy?->gradient_palette ?? \App\Enums\GradientPalette::OCEAN_BREEZE;
    $hexColors = $gradientPalette->getHexColors();
    $gradientFromHex = $hexColors['from'];
    $gradientToHex = $hexColors['to'];

    // Get brand color for dynamic styling
    $brandColor = $academy?->brand_color ?? \App\Enums\TailwindColor::SKY;
    $brandColorHex = $brandColor->getHexValue(500);
    $brandColorLightHex = $brandColor->getHexValue(200);

    // Get reviews items from academy
    $reviews = $academy?->reviews_items ?? [];

    // Helper function to get avatar URL
    $getAvatarUrl = function($avatar) {
        if (empty($avatar)) {
            return 'https://ui-avatars.com/api/?name=User&background=random&size=80';
        }
        if (str_starts_with($avatar, 'http')) {
            return $avatar;
        }
        return asset('storage/' . $avatar);
    };
@endphp

@if(count($reviews) > 0)
<!-- Testimonials Section - Template 3: Classic Design with 2 Items Per Slide -->
<section id="testimonials" class="py-16 sm:py-18 lg:py-20 relative overflow-hidden" role="region" aria-labelledby="testimonials-heading">
  <!-- Subtle Gradient Background -->
  <div class="absolute inset-0" style="background: linear-gradient(to bottom right, {{ $gradientFromHex }}33, #f9fafb, {{ $gradientToHex }}33);"></div>

  <div class="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="text-center md:text-right mb-8 sm:mb-10 lg:mb-12">
      <h2 id="testimonials-heading" class="text-2xl sm:text-3xl font-bold text-gray-900 mb-2 sm:mb-3">{{ $heading ?? 'آراء طلابنا' }}</h2>
      <p class="text-sm sm:text-base text-gray-600 max-w-2xl mx-auto md:mx-0">
        {{ $subheading ?? 'اكتشف تجارب طلابنا الناجحة وكيف ساعدتهم في تحقيق أهدافهم التعليمية' }}
      </p>
    </div>

    <!-- Testimonials Carousel with 2 Items Per Slide -->
    <div class="testimonials-carousel relative" data-brand-color="{{ $brandColorHex }}" data-brand-color-light="{{ $brandColorLightHex }}" data-items-mobile="1" data-items-tablet="2" data-items-desktop="2">
      <!-- Carousel Container -->
      <div class="carousel-container overflow-hidden py-6 px-2">
        <div id="testimonials-track" class="flex transition-transform duration-300 ease-in-out">
        @foreach($reviews as $review)
        <div class="carousel-item flex-shrink-0 w-full md:w-1/2 px-4">
          <div class="testimonial-card">
            <div class="testimonial-header">
              <div class="testimonial-avatar">
                <img src="{{ $getAvatarUrl($review['avatar'] ?? null) }}" alt="{{ $review['name'] }}">
              </div>
              <div class="testimonial-info">
                <h4 class="testimonial-name">{{ $review['name'] }}</h4>
                <p class="testimonial-role">{{ $review['role'] ?? '' }}</p>
              </div>
            </div>
            <div class="testimonial-rating">
              @for($i = 1; $i <= 5; $i++)
                @if($i <= ($review['rating'] ?? 5))
                  <i class="ri-star-fill"></i>
                @else
                  <i class="ri-star-line"></i>
                @endif
              @endfor
            </div>
            <p class="testimonial-content">
              "{{ $review['content'] }}"
            </p>
          </div>
        </div>
        @endforeach
        </div>
      </div>

      <!-- Navigation Buttons - Simple Transition -->
      <button id="carousel-prev" class="carousel-nav-btn absolute start-2 md:start-4 lg:start-[-4rem] z-10 w-10 h-10 md:w-12 md:h-12 bg-white rounded-lg shadow-md hover:bg-gray-50 flex items-center justify-center transition-colors duration-200" style="top: 50%; transform: translateY(-50%); color: {{ $brandColorHex }};">
        <i class="ri-arrow-right-s-line text-xl ltr:rotate-180"></i>
      </button>
      <button id="carousel-next" class="carousel-nav-btn absolute end-2 md:end-4 lg:end-[-4rem] z-10 w-10 h-10 md:w-12 md:h-12 bg-white rounded-lg shadow-md hover:bg-gray-50 flex items-center justify-center transition-colors duration-200" style="top: 50%; transform: translateY(-50%); color: {{ $brandColorHex }};">
        <i class="ri-arrow-left-s-line text-xl ltr:rotate-180"></i>
      </button>

      <!-- Pagination Dots - Increased Gap -->
      <div id="carousel-dots" class="flex justify-center items-center gap-3 mt-6">
        <!-- Dots will be generated by JavaScript -->
      </div>
    </div>
  </div>
</section>
@endif
